/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace DragonBallMarketplace {
  export type ListDetailStruct = {
    author: AddressLike;
    price: BigNumberish;
    tokenId: BigNumberish;
  };

  export type ListDetailStructOutput = [
    author: string,
    price: bigint,
    tokenId: bigint
  ] & { author: string; price: bigint; tokenId: bigint };
}

export interface DragonBallMarketplaceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "buyNft"
      | "getListedNft"
      | "listNft"
      | "onERC721Received"
      | "owner"
      | "renounceOwnership"
      | "setNft"
      | "setTax"
      | "transferOwnership"
      | "unlistNft"
      | "updateListingNftPrice"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BuyNFT"
      | "ListNFT"
      | "OwnershipTransferred"
      | "SetNFT"
      | "SetTax"
      | "UnlistNFT"
      | "UpdateListingNFTPrice"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "buyNft",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getListedNft",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "listNft",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC721Received",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "setNft", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "setTax",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unlistNft",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateListingNftPrice",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;

  decodeFunctionResult(functionFragment: "buyNft", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getListedNft",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "listNft", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "onERC721Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setNft", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setTax", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unlistNft", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateListingNftPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace BuyNFTEvent {
  export type InputTuple = [
    _from: AddressLike,
    _tokenId: BigNumberish,
    _price: BigNumberish
  ];
  export type OutputTuple = [_from: string, _tokenId: bigint, _price: bigint];
  export interface OutputObject {
    _from: string;
    _tokenId: bigint;
    _price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ListNFTEvent {
  export type InputTuple = [
    _from: AddressLike,
    _tokenId: BigNumberish,
    _price: BigNumberish
  ];
  export type OutputTuple = [_from: string, _tokenId: bigint, _price: bigint];
  export interface OutputObject {
    _from: string;
    _tokenId: bigint;
    _price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SetNFTEvent {
  export type InputTuple = [_nft: AddressLike];
  export type OutputTuple = [_nft: string];
  export interface OutputObject {
    _nft: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SetTaxEvent {
  export type InputTuple = [_tax: BigNumberish];
  export type OutputTuple = [_tax: bigint];
  export interface OutputObject {
    _tax: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnlistNFTEvent {
  export type InputTuple = [_from: AddressLike, _tokenId: BigNumberish];
  export type OutputTuple = [_from: string, _tokenId: bigint];
  export interface OutputObject {
    _from: string;
    _tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdateListingNFTPriceEvent {
  export type InputTuple = [_tokenId: BigNumberish, _price: BigNumberish];
  export type OutputTuple = [_tokenId: bigint, _price: bigint];
  export interface OutputObject {
    _tokenId: bigint;
    _price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DragonBallMarketplace extends BaseContract {
  connect(runner?: ContractRunner | null): DragonBallMarketplace;
  waitForDeployment(): Promise<this>;

  interface: DragonBallMarketplaceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  buyNft: TypedContractMethod<[_tokenId: BigNumberish], [void], "payable">;

  getListedNft: TypedContractMethod<
    [],
    [DragonBallMarketplace.ListDetailStructOutput[]],
    "view"
  >;

  listNft: TypedContractMethod<
    [_tokenId: BigNumberish, _price: BigNumberish],
    [void],
    "nonpayable"
  >;

  onERC721Received: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike],
    [string],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setNft: TypedContractMethod<[_nft: AddressLike], [void], "nonpayable">;

  setTax: TypedContractMethod<[_tax: BigNumberish], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unlistNft: TypedContractMethod<
    [_tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateListingNftPrice: TypedContractMethod<
    [_tokenId: BigNumberish, _price: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "buyNft"
  ): TypedContractMethod<[_tokenId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "getListedNft"
  ): TypedContractMethod<
    [],
    [DragonBallMarketplace.ListDetailStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "listNft"
  ): TypedContractMethod<
    [_tokenId: BigNumberish, _price: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "onERC721Received"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setNft"
  ): TypedContractMethod<[_nft: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTax"
  ): TypedContractMethod<[_tax: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unlistNft"
  ): TypedContractMethod<[_tokenId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateListingNftPrice"
  ): TypedContractMethod<
    [_tokenId: BigNumberish, _price: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "BuyNFT"
  ): TypedContractEvent<
    BuyNFTEvent.InputTuple,
    BuyNFTEvent.OutputTuple,
    BuyNFTEvent.OutputObject
  >;
  getEvent(
    key: "ListNFT"
  ): TypedContractEvent<
    ListNFTEvent.InputTuple,
    ListNFTEvent.OutputTuple,
    ListNFTEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SetNFT"
  ): TypedContractEvent<
    SetNFTEvent.InputTuple,
    SetNFTEvent.OutputTuple,
    SetNFTEvent.OutputObject
  >;
  getEvent(
    key: "SetTax"
  ): TypedContractEvent<
    SetTaxEvent.InputTuple,
    SetTaxEvent.OutputTuple,
    SetTaxEvent.OutputObject
  >;
  getEvent(
    key: "UnlistNFT"
  ): TypedContractEvent<
    UnlistNFTEvent.InputTuple,
    UnlistNFTEvent.OutputTuple,
    UnlistNFTEvent.OutputObject
  >;
  getEvent(
    key: "UpdateListingNFTPrice"
  ): TypedContractEvent<
    UpdateListingNFTPriceEvent.InputTuple,
    UpdateListingNFTPriceEvent.OutputTuple,
    UpdateListingNFTPriceEvent.OutputObject
  >;

  filters: {
    "BuyNFT(address,uint256,uint256)": TypedContractEvent<
      BuyNFTEvent.InputTuple,
      BuyNFTEvent.OutputTuple,
      BuyNFTEvent.OutputObject
    >;
    BuyNFT: TypedContractEvent<
      BuyNFTEvent.InputTuple,
      BuyNFTEvent.OutputTuple,
      BuyNFTEvent.OutputObject
    >;

    "ListNFT(address,uint256,uint256)": TypedContractEvent<
      ListNFTEvent.InputTuple,
      ListNFTEvent.OutputTuple,
      ListNFTEvent.OutputObject
    >;
    ListNFT: TypedContractEvent<
      ListNFTEvent.InputTuple,
      ListNFTEvent.OutputTuple,
      ListNFTEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SetNFT(address)": TypedContractEvent<
      SetNFTEvent.InputTuple,
      SetNFTEvent.OutputTuple,
      SetNFTEvent.OutputObject
    >;
    SetNFT: TypedContractEvent<
      SetNFTEvent.InputTuple,
      SetNFTEvent.OutputTuple,
      SetNFTEvent.OutputObject
    >;

    "SetTax(uint256)": TypedContractEvent<
      SetTaxEvent.InputTuple,
      SetTaxEvent.OutputTuple,
      SetTaxEvent.OutputObject
    >;
    SetTax: TypedContractEvent<
      SetTaxEvent.InputTuple,
      SetTaxEvent.OutputTuple,
      SetTaxEvent.OutputObject
    >;

    "UnlistNFT(address,uint256)": TypedContractEvent<
      UnlistNFTEvent.InputTuple,
      UnlistNFTEvent.OutputTuple,
      UnlistNFTEvent.OutputObject
    >;
    UnlistNFT: TypedContractEvent<
      UnlistNFTEvent.InputTuple,
      UnlistNFTEvent.OutputTuple,
      UnlistNFTEvent.OutputObject
    >;

    "UpdateListingNFTPrice(uint256,uint256)": TypedContractEvent<
      UpdateListingNFTPriceEvent.InputTuple,
      UpdateListingNFTPriceEvent.OutputTuple,
      UpdateListingNFTPriceEvent.OutputObject
    >;
    UpdateListingNFTPrice: TypedContractEvent<
      UpdateListingNFTPriceEvent.InputTuple,
      UpdateListingNFTPriceEvent.OutputTuple,
      UpdateListingNFTPriceEvent.OutputObject
    >;
  };
}
