/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DragonBall__factory } from "./DragonBall__factory";
export { IDragonBall__factory } from "./IDragonBall__factory";
